name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Change permissions for all files in repository
        run: |
          chmod -R 777 .

      - name: Remove old test build
        run: |
          rm ./unit_tests/test
          rm ./unit_tests/test.o

      - name: Remove old build
        run: |
          rm ./main.o
          rm ./assembler
          rm ./pre_assembler.o

      - name: Build project
        run: make 2>&1 | tee build_output.txt

      - name: Check for warnings
        run: |
          if grep -iq "warning:" build_output.txt; then
            cat build_output.txt
            echo "Warnings found in build output"
            exit 1
          else
            echo "No warnings found in build output"
          fi

      - name: Build and test
        run: |
          make -C unit_tests
          ./unit_tests/test
          test_result=$?
          echo "Test result: $test_result"
          exit $test_result